name: cutipie
description: "cutipie mobile client"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  google_fonts: 6.2.1
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  auto_route: ^9.2.2
  flutter_svg: 2.0.10+1
  logger: any
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  collection: 1.18.0
  gap: 3.0.1
  shimmer: 3.0.0
  http: 1.2.2
  shared_preferences: 2.2.3
  flutter_slidable: 3.1.1
  flutter_riverpod: ^2.5.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  in_app_purchase: ^3.2.0
  app_settings: ^5.1.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  google_mobile_ads: ^5.2.0
  permission_handler: ^11.3.1
  icons_launcher: ^3.0.0
  share_plus: ^10.1.2

  record: ^5.2.0

  path_provider: ^2.1.1

  flutter_native_splash: ^2.4.2
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  auto_route_generator: ^9.0.0
  freezed: 2.5.2
  json_serializable: 6.8.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icon/
    - assets/images/
